server:
  port: 8082
spring:
  application:
    name: userServer
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  jpa:
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8081/eureka
